site_name: База знаний по FPV
site_url: https://get-the-manual.github.io/fpv/
site_description: >-
  Здесь хранится базовая информация и накопленный опыт сообщества увлекающегося сборкой и полетами на дронах (квадрокоптерах) в FPV  режиме. Все исключительно в целях хобби.

# Repository
repo_name: get-the-manual/fpv
repo_url: https://github.com/get-the-manual/fpv
edit_uri: edit/main/docs/

plugins:
  - search
  - autorefs
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - attr_list
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.view
    - content.action.edit
  icon:
    edit: material/pencil 
    view: material/eye

extra:
  analytics:
      provider: google
      property: G-1M1HCQQL63
  consent:
    title: Cookie consent
    description: >-
      Мы используем куки для аналитики. Нажимая “Принять”, вы
      помогаете нам улучшать документацию.

nav:
  - Главная страница: index.md
  - Дроны:
    - Общая информация: 00_Drones/00_Obshhaya_informatsiya.md
    - Модели:
      - BETAFPV:
        - Общая информация: 00_Drones/01_Models/Betafpv/00_Obshhaya_informatsiya.md
        - Cetus X:
          - Общее: 00_Drones/01_Models/Betafpv/10_Cetus_X/10_Obshhee.md
          - Замена штатных антенн: 00_Drones/01_Models/Betafpv/10_Cetus_X/20_Zamena_shtatnyh_antenn.md
          - Кабель переходник: 00_Drones/01_Models/Betafpv/10_Cetus_X/30_Kabel_perehodnik.md
          - Замена рамы: 00_Drones/01_Models/Betafpv/10_Cetus_X/Zamena_ramy.md
          - Замена VTX C04: 00_Drones/01_Models/Betafpv/10_Cetus_X/Zamena_VTX_C04.md
          - Использование 2S баток: 00_Drones/01_Models/Betafpv/10_Cetus_X/Ispolzovanie_2S_batok.md
        - Компоненты:
          - Camera C03: 00_Drones/01_Models/Betafpv/90_Komponenty/Camera_C03.md
          - Camera VTX C04: 00_Drones/01_Models/Betafpv/90_Komponenty/Camera_VTX_C04.md
          - VTX M03: 00_Drones/01_Models/Betafpv/90_Komponenty/VTX_M03.md
        - Air65 Champion: 00_Drones/01_Models/Betafpv/Air65_Champion.md
        - Air65: 00_Drones/01_Models/Betafpv/Air65.md
        - Air75: 00_Drones/01_Models/Betafpv/Air75.md
        - Aquila16: 00_Drones/01_Models/Betafpv/Aquila16.md
        - Meteor65 Pro: 00_Drones/01_Models/Betafpv/Meteor65_Pro.md
        - Meteor75 Pro: 00_Drones/01_Models/Betafpv/Meteor75_Pro.md
        - Meteor85:
          - Общее: 00_Drones/01_Models/Betafpv/Meteor85/10_Obshhee.md
          - Переделка под DJI O4: 00_Drones/01_Models/Betafpv/Meteor85/Peredelka_pod_DJI_O4.md
      - DarwinFPV:
        - BabyApe Pro V2: 00_Drones/01_Models/DarwinFPV/BabyApe_Pro_V2.md
      - DJI:
        - DJI Neo: 00_Drones/01_Models/DJI/DJI_Neo.md
      - Happymodel:
        - Mobeetle6: 00_Drones/01_Models/Happymodel/Mobeetle6.md
        - mobula6: 00_Drones/01_Models/Happymodel/mobula6.md
        - mobula7: 00_Drones/01_Models/Happymodel/mobula7.md
      - HGLRC:
        - Draknight 2-inch: 00_Drones/01_Models/HGLRC/Draknight_2-inch.md
      - GepRC:
        - DarkStar22 O4 Pro: 
          - Общее: 00_Drones/01_Models/GepRC/DarkStar22/General.md
    - Сборка и пайка:
      - Общая информация: 00_Drones/10_Assemble_soldering/10_Obshhaya_informatsiya.md
      - Принадлежности: 00_Drones/10_Assemble_soldering/15_Prinadlezhnosti.md
      - Паяльники: 00_Drones/10_Assemble_soldering/20_Payalniki.md
      - Коннекторы: 00_Drones/10_Assemble_soldering/30_Konnektory.md
      - Провода: 00_Drones/10_Assemble_soldering/40_Provoda.md
    - Вопросы: 00_Drones/20_Voprosy.md
    - Вопросы видео: 00_Drones/23_Voprosy_video.md
    - Дрон кувыркается: 00_Drones/Drone_flips.md
    - VTX:
      - Общая информация: 00_Drones/20_VTX/00_Obshhaya_informatsiya.md
      - Модели:
        - RUSH TINY TANK Nano VTX: 00_Drones/20_VTX/02_Modeli/RUSH_TINY_TANK_Nano_VTX.md
      - Частоты VTX: 00_Drones/20_VTX/05_Chastoty_VTX.md
      - Кабель для проверки VTX и камеры: 00_Drones/20_VTX/10_Kabel dlya proverki VTX i kamery.md
      - Ремонт VTX: 00_Drones/20_VTX/30_Remont_VTX.md
      - Аналоговая VTX: 00_Drones/20_VTX/Analogovaya_VTX.md
      - Антенны на аналог: 00_Drones/20_VTX/Antenny_na_analog.md
      - Мощность и PIT: 00_Drones/20_VTX/Moshhnost_i_PIT.md
      - DJI O4:
        - Общее: 00_Drones/20_VTX/DJI_O4/10_Obshhee.md
        - Доработка: 00_Drones/20_VTX/DJI_O4/Dorabotka.md
        - Защита от воды: 00_Drones/20_VTX/DJI_O4/WaterProtect.md
      - OSD: 00_Drones/20_VTX/OSD.md
    - Полетник (FC):
      - Модели:
        - BETAFPV 1S модели (кратко): 00_Drones/22_FC/Modeli/BETAFPV_1S.md 
        - BETAFPV Air 5in1 4in1: 00_Drones/22_FC/Modeli/BETAFPV_Air_5in1_4in1.md
        - BETAFPV FC F4 1S 12A AIO: 00_Drones/22_FC/Modeli/BETAFPV_FC_F4_1S_12A_AIO.md
        - BETAFPV FC F4 1S 5A AIO: 00_Drones/22_FC/Modeli/BETAFPV_FC_F4_1S_5A_AIO.md
        - BETAFPV Matrix 1S 5in1: 00_Drones/22_FC/Modeli/BETAFPV_Matrix_1S_5in1.md
        - Happymodel CrazyG473 5in1: 00_Drones/22_FC/Modeli/Happymodel_CrazyG473_5in1.md
        - Happymodel ELRSF4 2G4: 00_Drones/22_FC/Modeli/Happymodel_ELRSF4_2G4.md
        - Happymodel SuperX 5in1: 00_Drones/22_FC/Modeli/Happymodel_SuperX_5in1.md
        - JHEMCU F435 NEO 1S AIO: 00_Drones/22_FC/Modeli/JHEMCU_F435_NEO_1S_AIO.md
        - WCRC F722 v3: 00_Drones/22_FC/Modeli/WCRC_F722_v3.md
      - Прошивка:
        - Общее: 00_Drones/22_FC/Proshivka/22_Obshhee.md
        - Betaflight:
          - Общее: 00_Drones/22_FC/Proshivka/30_Betaflight/10_Obshhee.md
          - Вопросы: 00_Drones/22_FC/Proshivka/30_Betaflight/15_Voprosy.md
          - Подключение к Configurator: 00_Drones/22_FC/Proshivka/30_Betaflight/17_Podklyuchenie_k_Configurator.md
          - Установка прошивки: 00_Drones/22_FC/Proshivka/30_Betaflight/20_Ustanovka_proshivki.md
          - Резервное копирование настроек: 00_Drones/22_FC/Proshivka/30_Betaflight/Backup.md
          - CLI (Command Line Interface): 00_Drones/22_FC/Proshivka/30_Betaflight/CLI.md
          - Команды CLI: 00_Drones/22_FC/Proshivka/30_Betaflight/Komandy_CLI.md
          - Anti-Gravity: 00_Drones/22_FC/Proshivka/30_Betaflight/Anti-Gravity.md
          - Resources: 00_Drones/22_FC/Proshivka/30_Betaflight/Resources.md
          - SoftSerial: 00_Drones/22_FC/Proshivka/30_Betaflight/SoftSerial.md
          - Trim: 00_Drones/22_FC/Proshivka/30_Betaflight/Trim.md
    - Связь с пультом:
      - Протоколы: 00_Drones/25_RC_Connect/05_Protokoly.md
      - ELRS: 00_Drones/25_RC_Connect/10_ELRS.md
      - LQ RSSI: 00_Drones/25_RC_Connect/LQ_RSSI.md
    - Камеры:
      - Общие вопросы: 00_Drones/30_Camera/General.md
      - Runcam Thumb Pro 4k: 00_Drones/30_Camera/50_Runcam Thumb Pro 4k.md
      - Конвертер analog в USB: 00_Drones/30_Camera/Konverter_analog_v_USB.md
    - Buzzer (пищалка): 00_Drones/30_Buzzer.md
    - Моторы:
      - Общее: 00_Drones/35_Motor/Obshhee.md
      - Сборка разборка: 00_Drones/35_Motor/Sborka_razborka.md
    - Пропеллеры:
      - Описание: 00_Drones/40_Prop/10_Opisanie.md
      - Снять надеть: 00_Drones/40_Prop/20_Snyat_nadet.md
      - Сравнение: 00_Drones/40_Prop/30_Sravnenie.md
    - Рамы:
      - Для 1S: 00_Drones/45_Frame/1S.md
    - ESC:
      - Общая информация: 00_Drones/50_ESC/General.md
    - Батареи: 00_Drones/Batarei.md
    - Защита от воды: 00_Drones/Zashhita_ot_vody.md
    - Режимы полета: 00_Drones/Rezhimy_poleta.md
    - GPS: 00_Drones/GPS.md
    - PID и фильтры: 00_Drones/PID.md
    - Rates: 00_Drones/Rates.md
    - LED: 00_Drones/LED.md
  - Аппаратура(Пульты):
    - Общая информация: 10_RC/01_Obshhaya_informatsiya.md
    - Модели:
      - Radiomaster:
        - Pocket:
          - Общая информация: 10_RC/10_Modeli/10_Radiomaster/01_Pocket/01_Obshhaya_informatsiya.md
          - Переключение колесом мощности VTX: 10_RC/10_Modeli/10_Radiomaster/01_Pocket/03_pereklyuchenie_kolesom_moshhnosti_VTX.md
          - Черепаха на SE: 10_RC/10_Modeli/10_Radiomaster/01_Pocket/05_Cherepaha_na_SE.md
          - Bind с Meteor85: 10_RC/10_Modeli/10_Radiomaster/01_Pocket/12_Bind_s_Meteor85.md
          - Стики и удлинители: 10_RC/10_Modeli/10_Radiomaster/01_Pocket/30_Stiki_i_udliniteli.md
          - Регулировка пружин: 10_RC/10_Modeli/10_Radiomaster/01_Pocket/Regulirovka_pruzhin.md
        - Boxer:
          - Общая информация: 10_RC/10_Modeli/10_Radiomaster/20_Boxer/01_Obshhaya_informatsiya.md
        - T8L:
          - Общая информация: 10_RC/10_Modeli/10_Radiomaster/T8L/01_General.md
        - Jumper T14:
          - Общая информация: 10_RC/10_Modeli/10_Radiomaster/Jumper_T14/01_Obshhaya_informatsiya.md
      - Betafpv:
        - LiteRadio:
          - Literadio2 3: 10_RC/10_Modeli/30_Betafpv/LiteRadio/01_Literadio2_3.md
          - Ремонт стиков: 10_RC/10_Modeli/30_Betafpv/LiteRadio/02_Remont_stikov.md
          - Замена резисторов: 10_RC/10_Modeli/30_Betafpv/LiteRadio/04_Zamena_rezistorov.md
          - Стики на датчиках Холла: 10_RC/10_Modeli/30_Betafpv/LiteRadio/10_Stiki_na_datchikah_Holla.md
          - Калибровка стиков: 10_RC/10_Modeli/30_Betafpv/LiteRadio/15_Kalibrovka_stikov.md
          - LiteRadio 2 SIM: 10_RC/10_Modeli/30_Betafpv/LiteRadio/20_LiteRadio_2_SIM.md
    - Общие вопросы: 10_RC/20_Voprosy.md
    - Edge TX:
      - Общие вопросы: 10_RC/25_Voprosy_Edge_TX.md
      - Edge TX Menu: 10_RC/30_Edge_TX_Menu.md
      - Пульт зависает: 10_RC/29_Pult_zavisaet.md
      - Настройка телеметрии: 10_RC/40_Nastrojka_telemetrii.md
      - Поиск дрона по RSSI: 10_RC/EdgeTX_DroneFinder.md
      - Озвучка низкого напряжения: 10_RC/Ozvuchka_nizkogo_napryazheniya.md
      - Таймер использования: 10_RC/EdgeTX_ArmTimer.md
    - FCC и LBT: 10_RC/27_FCC_i_LBT.md
  - Шлемы Очки:
    - Общее: 15_Goggles/10_Obshhee.md
    - Антенны на аналог: 15_Goggles/20_Antenny_na_analog.md
    - BETAFPV VR03: 15_Goggles/BETAFPV_VR03.md
    - DJI:
      - Общее: 15_Goggles/DJI/10_Obshhee.md
      - Лучшие очки для О4: 15_Goggles/DJI/Luchshie_ochki_dlya_O4.md
    - Eachine EV800D(M):
      - Общая информация: 15_Goggles/Eachine_EV800D(M)/Obshhaya informatsiya.md
      - Ремонт: 15_Goggles/Eachine_EV800D(M)/Remont.md
    - SKYZONE:
      - Общее: 15_Goggles/SKYZONE/Obshhee.md
  - Симуляторы:
    - Общие вопросы: 20_Simulyatory/03_Obshhie_voprosy.md
    - Какой сим выбрать: 20_Simulyatory/05_Kakoj_sim_vybrat.md
    - Сравнение: 20_Simulyatory/07_Sravnenie.md
    - Подключение аппаратуры к симулятору: 20_Simulyatory/20_Podklyuchenie_apparatury_k_simulyatoru.md
    - Дрифт в симуляторе: 20_Simulyatory/50_Drift_v_simulyatore.md
    - Сколько тренироваться: 20_Simulyatory/Skolko_trenirovatsya.md
    - DCL - The Game: 20_Simulyatory/DCL_-_The_Game.md
    - DRL: 20_Simulyatory/DRL.md
    - EreaDrone: 20_Simulyatory/EreaDrone.md
    - FPV Freerider: 20_Simulyatory/FPV_Freerider.md
    - FPV LOGIC: 20_Simulyatory/FPV_LOGIC.md
    - FPV SkyDive: 20_Simulyatory/FPV_SkyDive.md
    - Liftoff Microdrones: 20_Simulyatory/Liftoff_Microdrones.md
    - Liftoff: 20_Simulyatory/Liftoff.md
    - Real Drone Simulator: 20_Simulyatory/Real_Drone_Simulator.md
    - The Zone: 20_Simulyatory/The_Zone.md
    - TRYP FPV: 20_Simulyatory/TRYP_FPV.md
    - Uncrashed: 20_Simulyatory/Uncrashed.md
    - Velocidrone: 20_Simulyatory/Velocidrone.md
  - Полеты:
    - Обучение полетам: 30_Polety/10_Obuchenie_poletam.md
    - Обучение трюкам: 30_Polety/20_Obuchenie_tryukam.md
    - Вопросы: 30_Polety/24_Voprosy.md
    - Каталог Трюков: 30_Polety/26_Katalog_Tryukov.md
    - Гонки или соревнования:
      - Общее: 30_Polety/30_Gonki_ili_sorevnovaniya/10_Obshhee.md
      - IGOW: 30_Polety/30_Gonki_ili_sorevnovaniya/IGOW.md
      - RaceGOW: 30_Polety/30_Gonki_ili_sorevnovaniya/RaceGOW.md
      - VDT: 30_Polety/30_Gonki_ili_sorevnovaniya/VDT.md
      - FPV Battle (укр.): 30_Polety/30_Gonki_ili_sorevnovaniya/FPVBattle.md
      - weBLEEDfpv: 30_Polety/30_Gonki_ili_sorevnovaniya/weBLEEDfpv.md
    - Изготовление трасс:
      - Общее: 30_Polety/Izgotovlenie_trass/01_Obshhee.md
      - Для вупов: 30_Polety/Izgotovlenie_trass/Dlya_vupov.md
      - WhoopMANIA S1 Track1: 30_Polety/Izgotovlenie_trass/WhoopMANIA_S1_Track1.md
    - Серия трюков: 30_Polety/Seriya_tryukov.md
    - Стили Freestyle: 30_Polety/Stili_Freestyle.md
    - Freestyle в помещении: 30_Polety/Freestyle_v_pomeshhenii.md
  - Зарядные устройства:
    - Общая информация: 50_Charger/05_Obshhaya informatsiya.md
    - Зарядные устройства: 50_Charger/20_Zaryadnye_ustrojstva.md
    - Зарядка BetaFPV: 50_Charger/30_Zaryadka_BetaFPV.md
  - Аксессуары:
    - Сумки, футляры: 60_Aksessuary/10_Sumki_futlyary.md
  - Bind:
    - Введение: 60_Bind/10_Vvedenie.md
    - Протокол FrSky: 60_Bind/15_Protokol_FrSky.md
    - Протокол DJI: 60_Bind/16_Protokol_DJI.md
    - Протокол ELRS: 60_Bind/17_Protokol_ELRS.md
    - Подключение приемника: 60_Bind/18_Podklyuchenie_priemnika.md
    - Прошивка ELRS: 60_Bind/19_Proshivka_ELRS.md
    - Версия ELRS: 60_Bind/20_Versiya_ELRS.md
    - Режим Bind:
      - Дрона с UART: 60_Bind/40_Rezhim_Bind_drona_s_UART.md
      - Дрона с SPI: 60_Bind/50_Rezhim_Bind_drona_s_SPI.md
      - Пульта EdgeTX: 60_Bind/60_Rezhim_Bind_pulta_EdgeTX.md
      - Пульта Literadio3: 60_Bind/62_Rezhim_Bind_pulta_Literadio3.md
    - Bind фраза:
      - Дрона с UART: 60_Bind/44_Bind_fraza_drona_s_UART.md
      - Дрона с SPI: 60_Bind/54_Bind_fraza_drona_s_SPI.md
      - Пульта EdgeTX: 60_Bind/56_Bind_fraza_pulta_EdgeTX.md
      - Пульта LiteRadio: 60_Bind/58_Bind_fraza_pulta_LiteRadio.md
    - Проблемы: 60_Bind/70_Problemy.md
  - Что купить или собрать: 70_Chto_kupit_ili_sobrat.md
  - 3D модели:
    - Общее: 3D_models/General.md
    - Коробки для аккумуляторов: 3D_models/Battery_box.md
  - Видеомонтаж: Videomontazh.md
  - Мэмы: Memy.md
